# Generated by Django 2.0.5 on 2018-05-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='批准时间')),
                ('status', models.IntegerField(choices=[(0, '未审批'), (1, '已批准')], default=0, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100, verbose_name='书号')),
                ('name', models.CharField(max_length=100, verbose_name='书名')),
                ('brief', models.CharField(max_length=100, verbose_name='简介')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('image', models.ImageField(upload_to='books/image/', verbose_name='封面')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('count', models.IntegerField(verbose_name='库存')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='购买书籍'),
        ),
        migrations.AddField(
            model_name='bill',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User', verbose_name='下单人'),
        ),
    ]
