# Generated by Django 2.0.2 on 2018-05-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('status', models.IntegerField(choices=[(0, '未发货'), (1, '已发货')], default=0, verbose_name='订单状态')),
                ('address', models.CharField(default='', max_length=500, verbose_name='收获地址')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100, verbose_name='书号')),
                ('name', models.CharField(max_length=100, verbose_name='书名')),
                ('brief', models.CharField(max_length=100, verbose_name='简介')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('image', models.ImageField(upload_to='books/image/', verbose_name='封面')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('count', models.IntegerField(verbose_name='库存')),
                ('buy_count', models.IntegerField(default=0, verbose_name='购买人数')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='姓名')),
                ('username', models.CharField(default='', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=100, verbose_name='密码')),
                ('address', models.CharField(default='', max_length=500, verbose_name='地址')),
                ('phone', models.CharField(default='', max_length=200, verbose_name='电话号码')),
                ('money', models.IntegerField(default=0, verbose_name='金额')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='购买书籍'),
        ),
        migrations.AddField(
            model_name='bill',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User', verbose_name='下单人'),
        ),
    ]
